name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 6 * * *'  # Daily 6AM UTC build


jobs:

  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3
    - name: Cache PyPI
      uses: actions/cache@v2
      with:
        key: pip-lint-${{ hashFiles('requirements*.txt') }}
        path: ~/.cache/pip
        restore-keys: |
            pip-lint-
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: requirements-dev.txt
    - name: Install itself
      run: |
        pip install .
    - name: Run linters
      run: |
        make lint
      env:
        CI_LINT_RUN: 1
    - name: Install spell checker
      run: |
        sudo apt install libenchant-dev
        pip install -r requirements-doc.txt
    - name: Run docs spelling
      run: |
        towncrier --yes
        make doc-spelling
    - name: Prepare twine checker
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
    - name: Run twine checker
      run: |
        twine check dist/*

  unit:
    name: Unit
    needs: [lint]
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"    # - name: Cache
    - name: Cache PyPI
      uses: actions/cache@v2
      with:
        key: pip-ci-ubuntu-${{ matrix.python-version }}-${{ hashFiles('requirements*.txt') }}
        path: ${{ steps.pip-cache.outputs.dir }}
        restore-keys: |
            pip-ci-ubuntu-${{ matrix.python-version }}-
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: requirements-dev.txt
    - name: Run unittests
      env:
        COLOR: 'yes'
      run: |
        make test
    - name: Upload coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml
        flags: unit
        fail_ci_if_error: false

  deploy:
    name: Deploy on PyPI
    needs: [lint, unit]
    runs-on: ubuntu-latest
    # Run only on pushing a tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run:
        python -m pip install -U pip wheel build twine
    - name: Make dists
      run:
        python -m build
    - name: Release
      uses: aio-libs/create-release@v1.6.4
      with:
        changes_file: CHANGES.rst
        name: aiozipkin
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        artifact: ""
        version_file: aiozipkin/__init__.py
        fix_issue_regex: "\n?\\s*`#(\\d+) <https://github.com/aio-libs/aiozipkin/issues/\\1>`_"
        fix_issue_repl: " (#\\1)"
